import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [

  {
    _id: uuid(),
    "name": "Goku",
    "details": "Height: 7 inches, Material: PVC",
    "price": 39.99,
    "originalPrice": 2000,
    "category": "Dragon Ball Z",
    "instock": true,
    "discount": 0.2,
    "type": "hero",
    "rating": 4.5,
    "image_url": "https://shorturl.at/ltLMO"
  },
  {
    _id: uuid(),
    "name": "Luffy",
    "details": "Height: 6 inches, Material: PVC",
    "price": 29.99,
    "originalPrice": 2000,
    "category": "One Piece",
    "instock": false,
    "discount": 0.1,
    "type": "villain",
    "rating": 4.2,
    "image_url": "https://shorturl.at/hBKX7",
  },
  {
    _id: uuid(),
    "name": "Naruto Uzumaki",
    "details": "Height: 6 inches, Material: PVC",
    "price": 34.99,
    "originalPrice": 2000,
    "category": "Naruto",
    "instock": true,
    "discount": 0.15,
    "type": "hero",
    "rating": 4.4,
    "image_url": "https://shorturl.at/fCPU3",
  },
  {
    _id: uuid(),
    "name": "Ichigo Kurosaki",
    "details": "Height: 6 inches, Material: PVC",
    "price": 27.99,
    "originalPrice": 2000,
    "category": "Bleach",
    "instock": false,
    "discount": 0.05,
    "type": "hero",
    "rating": 4.1,
    "image_url": "https://shorturl.at/pAEN6",
  },
  {
    _id: uuid(),
    "name": "Sasuke Uchiha",
    "details": "Height: 6 inches, Material: PVC",
    "price": 29.99,
    "originalPrice": 2000,
    "category": "Naruto",
    "instock": false,
    "discount": 0.1,
    "type": "hero",
    "rating": 4.3,
    "image_url": "https://shorturl.at/mWY45"
  },
  {
    _id: uuid(),
    "name": "Vegeta",
    "details": "Height: 6 inches, Material: PVC",
    "price": 36.99,
    "originalPrice": 2000,
    "category": "Dragon Ball Z",
    "instock": true,
    "discount": 0.1,
    "type": "hero",
    "rating": 4.4,
    "image_url": "https://shorturl.at/hqKQZ"
  },
  {
    _id: uuid(),
    "name": "Eren Yeager",
    "details": "Height: 7 inches, Material: PVC",
    "price": 32.99,
    "originalPrice": 2000,
    "category": "Attack on Titan",
    "instock": true,
    "discount": 0.05,
    "type": "hero",
    "rating": 4.3,
    "image_url": "https://shorturl.at/fnMUX"
  },
  {
    _id: uuid(),
    "name": "Zoro",
    "details": "Height: 6 inches, Material: PVC",
    "price": 29.99,
    "originalPrice": 2000,
    "category": "One Piece",
    "instock": false,
    "discount": 0.1,
    "type": "hero",
    "rating": 4.2,
    "image_url": "https://shorturl.at/bcnOQ"
  },
  {
    _id: uuid(),
    "name": "Gon Freecss",
    "details": "Height: 6 inches, Material: PVC",
    "price": 31.99,
    "originalPrice": 2000,
    "category": "Hunter x Hunter",
    "instock": true,
    "discount": 0.1,
    "type": "hero",
    "rating": 4.3,
    "image_url": "https://shorturl.at/dhuX6"
  },
  {
    _id: uuid(),
    "name": "Saitama",
    "details": "Height: 7 inches, Material: PVC",
    "price": 39.99,
    "originalPrice": 2000,
    "category": "One Punch Man",
    "instock": true,
    "discount": 0.2,
    "type": "hero",
    "rating": 4.5,
    "image_url": "https://shorturl.at/knNPR"
  },
  {
    _id: uuid(),
    "name": "Gon Freecss",
    "details": "Height: 6 inches, Material: PVC",
    "price": 29.99,
    "originalPrice": 2000,
    "category": "Hunter x Hunter",
    "instock": false,
    "discount": 0.1,
    "type": "hero",
    "rating": 4.2,
    "image_url": "https://shorturl.at/nopr3"
  },
  {
    _id: uuid(),
    "name": "Levi Ackerman",
    "details": "Height: 6 inches, Material: PVC",
    "price": 34.99,
    "originalPrice": 2000,
    "category": "Attack on Titan",
    "instock": true,
    "discount": 0.15,
    "type": "hero",
    "rating": 4.4,
    "image_url": "https://shorturl.at/deryI"
  },
  {
    _id: uuid(),
    "name": "Sasuke Uchiha",
    "details": "Height: 6 inches, Material: PVC",
    "price": 32.99,
    "originalPrice": 2000,
    "category": "Naruto",
    "instock": false,
    "discount": 0.1,
    "type": "hero",
    "rating": 4.3,
    "image_url": "https://shorturl.at/jkq29"
  },
  {
    _id: uuid(),
    "name": "Roronoa Zoro",
    "details": "Height: 6 inches, Material: PVC",
    "price": 29.99,
    "originalPrice": 2000,
    "category": "One Piece",
    "instock": false,
    "discount": 0.05,
    "type": "hero",
    "rating": 4.2,
    "image_url": "https://shorturl.at/mWY45"
  },
  {
    _id: uuid(),
    "name": "Edward Elric",
    "details": "Height: 6 inches, Material: PVC",
    "price": 31.99,
    "originalPrice": 2000,
    "category": "Fullmetal Alchemist",
    "instock": true,
    "discount": 0.1,
    "type": "hero",
    "rating": 4.4,
    "image_url": "https://shorturl.at/mWY45"
  },
  {
    _id: uuid(),
    "name": "Natsu Dragneel",
    "details": "Height: 7 inches, Material: PVC",
    "price": 34.99,
    "originalPrice": 2000,
    "category": "Fairy Tail",
    "instock": false,
    "discount": 0.1,
    "type": "hero",
    "rating": 4.3,
    "image_url": "https://shorturl.at/mWY45"
  },
  {
    _id: uuid(),
    "name": "Killua Zoldyck",
    "details": "Height: 6 inches, Material: PVC",
    "price": 29.99,
    "originalPrice": 2000,
    "category": "Hunter x Hunter",
    "instock": true,
    "discount": 0.05,
    "type": "hero",
    "rating": 4.2,
    "image_url": "https://shorturl.at/mWY45"
  },
  {
    _id: uuid(),
    "name": "Grimmjow Jaegerjaquez",
    "details": "Height: 6 inches, Material: PVC",
    "price": 32.99,
    "originalPrice": 2000,
    "category": "Bleach",
    "instock": false,
    "discount": 0.1,
    "type": "villain",
    "rating": 4.4,
    "image_url": "https://shorturl.at/mWY45"
  },
  {
    _id: uuid(),
    "name": "Gon Freecss",
    "details": "Height: 6 inches, Material: PVC",
    "price": 29.99,
    "originalPrice": 2000,
    "category": "Hunter x Hunter",
    "instock": true,
    "discount": 0.1,
    "type": "hero",
    "rating": 4.2,
    "image_url": "https://shorturl.at/mWY45"
  },
  {
    _id: uuid(),
    "name": "Itachi Uchiha",
    "details": "Height: 6 inches, Material: PVC",
    "price": 34.99,
    "originalPrice": 2000,
    "category": "Naruto",
    "instock": false,
    "discount": 0.15,
    "type": "villain",
    "rating": 4.4,
    "image_url": "https://shorturl.at/mWY45"
  },
  {
    _id: uuid(),
    "name": "Monkey D. Luffy",
    "details": "Height: 6 inches, Material: PVC",
    "price": 29.99,
    "originalPrice": 2000,
    "category": "One Piece",
    "instock": true,
    "discount": 0.1,
    "type": "hero",
    "rating": 4.3,
    "image_url": "https://shorturl.at/mWY45"
  },
  {
    _id: uuid(),
    "name": "Ken Kaneki",
    "details": "Height: 6 inches, Material: PVC",
    "price": 32.99,
    "originalPrice": 2000,
    "category": "Tokyo Ghoul",
    "instock": false,
    "discount": 0.1,
    "type": "hero",
    "rating": 4.4,
    "image_url": "https://shorturl.at/mWY45"
  },
  {
    _id: uuid(),
    "name": "Todoroki Shoto",
    "details": "Height: 7 inches, Material: PVC",
    "price": 36.99,
    "originalPrice": 2000,
    "category": "My Hero Academia",
    "instock": true,
    "discount": 0.2,
    "type": "hero",
    "rating": 4.5,
    "image_url": "https://shorturl.at/mWY45"
  },
  {
    _id: uuid(),
    "name": "Yami Sukehiro",
    "details": "Height: 6 inches, Material: PVC",
    "price": 25.22,
    "originalPrice": 2000,
    "category": "Black Clover",
    "instock": false,
    "discount": 0.7,
    "type": "hero",
    "rating": 4.1,
    "image_url": "https://shorturl.at/mWY45"
  },
  {
    _id: uuid(),
    "name": "Sasuke Uchiha",
    "details": "Height: 6 inches, Material: PVC",
    "price": 32.99,
    "originalPrice": 2000,
    "category": "Naruto",
    "instock": false,
    "discount": 0.1,
    "type": "hero",
    "rating": 4.3,
    "image_url": "https://shorturl.at/mWY45"
  },
  {
    _id: uuid(),
    "name": "Roronoa Zoro",
    "details": "Height: 6 inches, Material: PVC",
    "price": 29.99,
    "originalPrice": 2000,
    "category": "One Piece",
    "instock": true,
    "discount": 0.05,
    "type": "hero",
    "rating": 4.2,
    "image_url": "https://shorturl.at/mWY45"
  },
  {
    _id: uuid(),
    "name": "Edward Elric",
    "details": "Height: 6 inches, Material: PVC",
    "price": 31.99,
    "originalPrice": 2000,
    "category": "Fullmetal Alchemist",
    "instock": false,
    "discount": 0.1,
    "type": "hero",
    "rating": 4.4,
    "image_url": "https://shorturl.at/mWY45"
  },
  {
    _id: uuid(),
    "name": "Natsu Dragneel",
    "details": "Height: 7 inches, Material: PVC",
    "price": 34.99,
    "originalPrice": 2000,
    "category": "Fairy Tail",
    "instock": true,
    "discount": 0.1,
    "type": "hero",
    "rating": 4.3,
    "image_url": "https://shorturl.at/mWY45"
  },
  {
    _id: uuid(),
    "name": "Killua Zoldyck",
    "details": "Height: 6 inches, Material: PVC",
    "price": 29.99,
    "originalPrice": 2000,
    "category": "Hunter x Hunter",
    "instock": false,
    "discount": 0.05,
    "type": "hero",
    "rating": 4.2,
    "image_url": "https://shorturl.at/mWY45"
  },
  {
    _id: uuid(),
    "name": "Grimmjow Jaegerjaquez",
    "details": "Height: 6 inches, Material: PVC",
    "price": 32.99,
    "originalPrice": 2000,
    "category": "Bleach",
    "instock": true,
    "discount": 0.1,
    "type": "villain",
    "rating": 4.4,
    "image_url": "https://shorturl.at/mWY45"
  },
  {
    "name": "Frieza",
    "details": "Height: 5'9\", Material: Unknown",
    "price": 39.99,
    "originalPrice": 3000,
    "category": "Dragon Ball Z",
    "instock": true,
    "discount": 0.2,
    "type": "villain",
    "rating": 4.8
  },
  {
    "name": "Madara Uchiha",
    "details": "Height: 6'0\", Material: Unknown",
    "price": 49.99,
    "originalPrice": 4000,
    "category": "Naruto",
    "instock": true,
    "discount": 0.15,
    "type": "villain",
    "rating": 4.7
  },
  {
    "name": "Hisoka Morow",
    "details": "Height: 6'2\", Material: Unknown",
    "price": 24.99,
    "originalPrice": 1500,
    "category": "Hunter x Hunter",
    "instock": false,
    "discount": 0.1,
    "type": "villain",
    "rating": 4.5
  },
  {
    "name": "Aizen Sosuke",
    "details": "Height: 6'1\", Material: Unknown",
    "price": 44.99,
    "originalPrice": 3500,
    "category": "Bleach",
    "instock": true,
    "discount": 0.25,
    "type": "villain",
    "rating": 4.6
  },
  {
    "name": "Meruem",
    "details": "Height: 6'6\", Material: Unknown",
    "price": 29.99,
    "originalPrice": 2000,
    "category": "Hunter x Hunter",
    "instock": true,
    "discount": 0.2,
    "type": "villain",
    "rating": 4.4
  }

]
